@extends('layouts.app')
@section('title',__('Users'))
@section('content')
<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><h1 class="mb-0">{{ __('Users') }}</h1><a class="btn btn-primary" href="{{ route('users.create') }}"><i class="bi bi-person-plus" aria-hidden="true"></i> {{ __('Add User') }}</a></div>
<form class="card card-body mb-3" method="get"><div class="row g-2"><div class="col-md-4"><label class="form-label" for="search"><i class="bi bi-search" aria-hidden="true"></i> {{ __('Search name, email or designation') }}</label><input class="form-control" id="search" name="search" value="{{ $search }}"></div><div class="col-md-2"><label class="form-label" for="unit"><i class="bi bi-building" aria-hidden="true"></i> {{ __('Unit') }}</label><select class="form-select" id="unit" name="unit"><option value="">{{ __('All units') }}</option>@foreach(config('scheduler.user_units') as $unit)<option value="{{ $unit }}" @selected(request('unit')===$unit)>{{ $unit }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label" for="role"><i class="bi bi-shield-lock" aria-hidden="true"></i> {{ __('Role') }}</label><select class="form-select" id="role" name="role"><option value="">{{ __('All roles') }}</option>@foreach(\App\Enums\UserRole::options() as $role)<option value="{{ $role['value'] }}" @selected(request('role')===$role['value'])>{{ $role['label'] }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label" for="status"><i class="bi bi-check-circle" aria-hidden="true"></i> {{ __('Status') }}</label><select class="form-select" id="status" name="status"><option value="">{{ __('All') }}</option><option value="active" @selected(request('status')==='active')>{{ __('Active') }}</option><option value="inactive" @selected(request('status')==='inactive')>{{ __('Inactive') }}</option></select></div><div class="col-md-2 align-self-end"><button class="btn btn-primary"><i class="bi bi-search" aria-hidden="true"></i> {{ __('Search') }}</button> <a href="{{ route('users.index') }}" class="btn btn-outline-secondary"><i class="bi bi-arrow-counterclockwise" aria-hidden="true"></i> {{ __('Clear') }}</a></div></div></form>
<div class="card"><div class="table-responsive"><table class="table table-vcenter mb-0"><thead><tr><th>#</th><th>{{ __('Name / Email') }}</th><th>{{ __('Designation') }}</th><th>{{ __('Unit') }}</th><th>{{ __('Role') }}</th><th>{{ __('Status') }}</th><th>{{ __('Last Login') }}</th><th>{{ __('Actions') }}</th></tr></thead><tbody>
@forelse($users as $user)<tr><td>{{ $users->firstItem()+$loop->index }}</td><td><strong>{{ $user->name }}</strong><br><small>{{ $user->email }}</small></td><td>{{ __($user->designation?->name ?? 'Not assigned') }}</td><td>{{ $user->unit ?? __('Not assigned') }}</td><td>{{ $user->role->label() }}</td><td>{{ $user->is_active ? __('Active') : __('Inactive') }}</td><td>{{ $user->last_login_at?->format('d M Y, h:i A') ?? __('Never') }}</td><td><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-primary btn-sm" href="{{ route('users.edit',$user) }}"><i class="bi bi-pencil-square" aria-hidden="true"></i> {{ __('Edit / Password') }}</a>@unless(auth()->id()===$user->id)<a class="btn btn-outline-danger btn-sm" href="{{ route('users.confirm-delete',$user) }}"><i class="bi bi-trash3" aria-hidden="true"></i> {{ __('Delete') }}</a>@endunless</div></td></tr>@empty<tr><td colspan="8" class="text-center text-secondary py-4">{{ __('No users found.') }}</td></tr>@endforelse
</tbody></table></div><div class="card-footer">@include('shared.pagination',['paginator'=>$users])</div></div>
@endsection
