@extends('layouts.app')
@section('title',__('Change Password'))
@section('content')
<h1 class="mb-3">{{ __('Change Password') }}</h1>
<form class="card card-body" method="post" action="{{ route('staff-profile.update-password') }}" style="max-width:600px">@csrf @method('PUT')
<label class="form-label" for="current_password"><i class="bi bi-key" aria-hidden="true"></i> {{ __('Current Password') }}</label><div class="password-control"><input class="form-control mb-3" type="password" id="current_password" name="current_password" autocomplete="current-password" required><button type="button" class="password-toggle" data-password-toggle data-show-label="{{ __('Show password') }}" data-hide-label="{{ __('Hide password') }}" aria-label="{{ __('Show password') }}" title="{{ __('Show password') }}" aria-pressed="false" hidden><i class="bi bi-eye" aria-hidden="true"></i></button></div>
<label class="form-label" for="password"><i class="bi bi-lock" aria-hidden="true"></i> {{ __('New Password') }}</label><div class="password-control"><input class="form-control" type="password" id="password" name="password" autocomplete="new-password" minlength="8" required><button type="button" class="password-toggle" data-password-toggle data-show-label="{{ __('Show password') }}" data-hide-label="{{ __('Hide password') }}" aria-label="{{ __('Show password') }}" title="{{ __('Show password') }}" aria-pressed="false" hidden><i class="bi bi-eye" aria-hidden="true"></i></button></div><p class="form-hint mb-3">{{ __('Use at least 8 characters, with uppercase/lowercase letters, a number and a symbol.') }}</p>
<label class="form-label" for="password_confirmation"><i class="bi bi-lock" aria-hidden="true"></i> {{ __('Confirm New Password') }}</label><div class="password-control"><input class="form-control mb-3" type="password" id="password_confirmation" name="password_confirmation" autocomplete="new-password" required><button type="button" class="password-toggle" data-password-toggle data-show-label="{{ __('Show password') }}" data-hide-label="{{ __('Hide password') }}" aria-label="{{ __('Show password') }}" title="{{ __('Show password') }}" aria-pressed="false" hidden><i class="bi bi-eye" aria-hidden="true"></i></button></div>
<div><button class="btn btn-primary"><i class="bi bi-key" aria-hidden="true"></i> {{ __('Update Password') }}</button> <a class="btn btn-outline-secondary" href="{{ route('dashboard') }}"><i class="bi bi-arrow-left" aria-hidden="true"></i> {{ __('Back') }}</a></div></form>
@endsection
