@extends('layouts.app')
@section('title',$schedule->exists ? __('Edit Schedule'):__('Add Schedule'))
@section('content')
<div class="d-flex justify-content-between gap-2 mb-3"><h1 class="page-title">{{ $schedule->exists ? __('Edit Exam Schedule'):__('Add Exam Schedule') }}</h1><a href="{{ route('schedules.index') }}" class="btn btn-outline-secondary"><i class="bi bi-arrow-left" aria-hidden="true"></i> {{ __('Back') }}</a></div>
<form class="card card-body" method="post" action="{{ $schedule->exists ? route('schedules.update',$schedule) : route('schedules.store') }}">@csrf @if($schedule->exists)@method('PUT')<input type="hidden" name="version" value="{{ old('version',$schedule->version) }}">@endif
@if($schedule->exists && !in_array($schedule->unit, config('scheduler.units'), true))<div class="alert alert-warning">{{ __('Select a current unit before saving this older schedule.') }} ({{ $schedule->unit }})</div>@endif
<p class="text-secondary">{{ __('Bengali or English text may be entered in all text fields.') }}</p>
<div class="row g-3">
<div class="col-md-6"><label class="form-label required" for="unit"><i class="bi bi-building" aria-hidden="true"></i> {{ __('Unit') }}</label><select class="form-select" id="unit" name="unit" required><option value="">{{ __('Select unit') }}</option>@foreach(config('scheduler.units') as $unit)<option value="{{ $unit }}" @selected(old('unit',$schedule->unit)===$unit)>{{ $unit }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label required" for="exam_type"><i class="bi bi-list-check" aria-hidden="true"></i> {{ __('Exam Type') }}</label><select class="form-select" id="exam_type" name="exam_type" required data-exam-type><option value="">{{ __('Select exam type') }}</option>@foreach(config('scheduler.types') as $code=>$type)<option value="{{ $code }}" data-viva="{{ $type['viva'] ? 1:0 }}" @selected(old('exam_type',$schedule->exam_type)===$code)>{{ __($type['label']) }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label" for="reference"><i class="bi bi-hash" aria-hidden="true"></i> {{ __('Post Code (Optional)') }}</label><input class="form-control" name="reference" id="reference" maxlength="100" value="{{ old('reference',$schedule->reference) }}"></div>
<div class="col-md-8"><label class="form-label required" for="post_name"><i class="bi bi-person-badge" aria-hidden="true"></i> {{ __('Post Name') }}</label><input class="form-control" name="post_name" id="post_name" maxlength="200" required value="{{ old('post_name',$schedule->post_name) }}"></div>
<div class="col-12"><label class="form-label required" for="ministry"><i class="bi bi-building" aria-hidden="true"></i> {{ __('Ministry/Organization') }}</label><input class="form-control" name="ministry" id="ministry" maxlength="200" required value="{{ old('ministry',$schedule->ministry) }}"></div>
<div class="col-md-6"><label class="form-label" for="advertisement_number"><i class="bi bi-file-earmark-text" aria-hidden="true"></i> {{ __('Advertisement Number (Optional)') }}</label><input class="form-control" name="advertisement_number" id="advertisement_number" maxlength="100" value="{{ old('advertisement_number',$schedule->advertisement_number) }}"></div>
<div class="col-md-6"><label class="form-label" for="advertisement_year"><i class="bi bi-calendar-event" aria-hidden="true"></i> {{ __('Advertisement Year (Optional)') }}</label><input class="form-control" type="text" inputmode="numeric" pattern="[0-9০-৯]{4}" name="advertisement_year" id="advertisement_year" maxlength="4" value="{{ old('advertisement_year',\App\Support\Ui::digits($schedule->advertisement_year ?? '')) }}"><small class="form-hint">{{ __('Use four digits, e.g. 2026 or ২০২৬.') }}</small></div>
<div class="col-md-4"><label class="form-label required" for="exam_date"><i class="bi bi-calendar3" aria-hidden="true"></i> {{ __('Exam Date') }}</label><input class="form-control" type="date" name="exam_date" id="exam_date" required value="{{ old('exam_date',$schedule->exam_date?->format('Y-m-d')) }}"></div>
@foreach(['start_time'=>'Start Time (Optional)','end_time'=>'End Time (Optional)'] as $field=>$label)<div class="col-6 col-md-4"><label class="form-label" for="{{ $field }}"><i class="bi bi-clock" aria-hidden="true"></i> {{ __($label) }}</label><input class="form-control" type="time" id="{{ $field }}" name="{{ $field }}" value="{{ old($field,$schedule->$field ? substr($schedule->$field,0,5):'') }}"><small class="form-hint">{{ __('Bangladesh time (UTC+6)') }}</small></div>@endforeach
<div class="col-md-4"><label class="form-label" for="candidate_count"><i class="bi bi-people" aria-hidden="true"></i> {{ __('Number of Candidates (Optional)') }}</label><input class="form-control" type="text" inputmode="numeric" pattern="[0-9০-৯]+" maxlength="8" id="candidate_count" name="candidate_count" value="{{ old('candidate_count',$schedule->candidate_count) }}"></div>
<div class="col-md-4" data-count="center"><label class="form-label" for="center_count"><i class="bi bi-geo-alt" aria-hidden="true"></i> {{ __('Number of Exam Centers (Non-Viva) (Optional)') }}</label><input class="form-control" type="text" inputmode="numeric" pattern="[0-9০-৯]+" maxlength="6" id="center_count" name="center_count" value="{{ old('center_count',$schedule->center_count) }}"></div>
<div class="col-md-4" data-count="board"><label class="form-label required" for="board_count"><i class="bi bi-person-workspace" aria-hidden="true"></i> {{ __('Number of Boards') }}</label><input class="form-control" type="text" inputmode="numeric" pattern="[0-9০-৯]+" maxlength="6" id="board_count" name="board_count" value="{{ old('board_count',$schedule->board_count) }}"></div>
<div class="col-md-4"><label class="form-label required" for="status"><i class="bi bi-check-circle" aria-hidden="true"></i> {{ __('Status') }}</label><select class="form-select" name="status" id="status" required>@foreach(config('scheduler.statuses') as $code=>$label)<option value="{{ $code }}" @selected(old('status',$schedule->status)===$code)>{{ __($label) }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label" for="notes"><i class="bi bi-chat-left-text" aria-hidden="true"></i> {{ __('Notes/Remarks (Optional)') }}</label><textarea class="form-control" id="notes" name="notes" rows="3" maxlength="4000">{{ old('notes',$schedule->notes) }}</textarea></div>
<div class="col-12"><button class="btn btn-primary"><i class="bi bi-check2-circle" aria-hidden="true"></i> {{ __('Save Schedule') }}</button></div>
</div></form>
@endsection
