@extends('layouts.app')
@section('title', $isDashboard ? __('Dashboard') : __('Exam Schedules'))
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h1 class="page-title">{{ $isDashboard ? __("This Week's Schedule") : __('Exam Schedules') }}</h1><div class="text-secondary">@if($filters['from']){{ \App\Support\Ui::date($filters['from'],'d M Y') }} – {{ \App\Support\Ui::date($filters['to'],'d M Y') }}@else{{ __('All dates') }}@endif · {{ __('Bangladesh time') }}</div></div>@can('edit-schedules')<a class="btn btn-primary" href="{{ route('schedules.create') }}">{{ __('Add Exam Schedule') }}</a>@endcan</div>
<div class="row g-3 mb-3">@foreach(['exams'=>'Exams','units'=>'Units'] as $key=>$label)<div class="col-6"><div class="card card-body"><div class="text-secondary">{{ __($label) }}</div><div class="h1 mb-0">{{ \App\Support\Ui::number($summary[$key]) }}</div></div></div>@endforeach</div>
<form class="card card-body mb-3 d-print-none" method="get" action="{{ route($isDashboard ? 'dashboard' : 'schedules.index') }}"><input type="hidden" name="display" value="{{ $filters['display'] }}"><div class="row g-3">
<div class="col-12 col-md-4 col-lg-2"><label class="form-label" for="date"><i class="bi bi-calendar3" aria-hidden="true"></i> {{ __('Single Date') }}</label><input class="form-control" type="date" id="date" name="date" value="{{ request('date') }}"><small class="form-hint text-nowrap" title="{{ __('A single date overrides From and To.') }}">{{ __('Overrides the date range') }}</small></div>
<div class="col-6 col-md-4 col-lg-2"><label class="form-label" for="from"><i class="bi bi-calendar3" aria-hidden="true"></i> {{ __('From') }}</label><input class="form-control" type="date" id="from" name="from" value="{{ $filters['from'] }}"></div><div class="col-6 col-md-4 col-lg-2"><label class="form-label" for="to"><i class="bi bi-calendar3" aria-hidden="true"></i> {{ __('To') }}</label><input class="form-control" type="date" id="to" name="to" value="{{ $filters['to'] }}"></div>
<div class="col-12 col-md-4 col-lg-3"><label class="form-label" for="exam_type"><i class="bi bi-list-check" aria-hidden="true"></i> {{ __('Exam Type') }}</label><select class="form-select" id="exam_type" name="exam_type"><option value="">{{ __('All exam types') }}</option>@foreach(config('scheduler.types') as $code=>$type)<option value="{{ $code }}" @selected(($filters['exam_type'] ?? '')===$code)>{{ __($type['label']) }}</option>@endforeach</select></div>
<div class="col-12 col-md-4 col-lg-3"><label class="form-label" for="unit"><i class="bi bi-building" aria-hidden="true"></i> {{ __('Unit') }}</label><select class="form-select" id="unit" name="unit"><option value="">{{ __('All units') }}</option>@foreach(config('scheduler.units') as $unit)<option value="{{ $unit }}" @selected(($filters['unit'] ?? '')===$unit)>{{ $unit }}</option>@endforeach</select></div>
<div class="col-12 col-md-4"><label class="form-label" for="status"><i class="bi bi-check-circle" aria-hidden="true"></i> {{ __('Status') }}</label><select class="form-select" id="status" name="status"><option value="">{{ __('All statuses') }}</option>@foreach(config('scheduler.statuses') as $code=>$label)<option value="{{ $code }}" @selected(($filters['status'] ?? '')===$code)>{{ __($label) }}</option>@endforeach</select></div>
<div class="col-12 col-md-5"><label class="form-label" for="search"><i class="bi bi-search" aria-hidden="true"></i> {{ __('Search schedules') }}</label><input class="form-control" id="search" name="search" value="{{ $filters['search'] ?? '' }}" maxlength="200"></div>
<div class="col-12 col-md-3 align-self-end d-flex gap-2 filter-actions"><button class="btn btn-primary"><i class="bi bi-funnel" aria-hidden="true"></i> {{ __('Apply Filters') }}</button><a class="btn btn-outline-secondary" href="{{ route($isDashboard ? 'dashboard' : 'schedules.index') }}"><i class="bi bi-arrow-counterclockwise" aria-hidden="true"></i> {{ $isDashboard ? __('This Week') : __('Clear Filters') }}</a></div>
</div></form>
<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><span class="text-secondary small">{{ __('Statistics reflect all matching exams, not just this page.') }}</span><div class="d-flex flex-wrap gap-2 d-print-none">@foreach(['xlsx'=>'Export XLSX','pdf'=>'Export PDF','print'=>'Print'] as $format=>$label)<a class="btn btn-outline-primary btn-sm" @if($format==='print')target="_blank" rel="noopener"@endif href="{{ route('schedules.export',array_merge($filters,['format'=>$format,'page'=>null])) }}"><i class="bi bi-{{ ['xlsx'=>'file-earmark-excel','pdf'=>'file-earmark-pdf','print'=>'printer'][$format] }}" aria-hidden="true"></i> {{ __($label) }}</a>@endforeach</div></div>
<div class="d-flex flex-wrap gap-2 mb-3" role="group" aria-label="{{ __('Schedule display') }}">
@foreach(['flat'=>'Exam rows','grouped'=>'Date-wise rows'] as $mode=>$label)<a class="btn btn-sm {{ $filters['display']===$mode ? 'btn-primary':'btn-outline-primary' }}" @if($filters['display']===$mode)aria-current="true"@endif href="{{ route($isDashboard ? 'dashboard':'schedules.index',array_merge($filters,['display'=>$mode,'page'=>null])) }}">{{ __($label) }}</a>@endforeach
</div>
@php($previousDate = null)
@php($dateSerial = 0)
<div class="card"><div class="table-responsive"><table class="table table-bordered table-vcenter schedule-table mb-0"><thead><tr>@if($filters['display']==='grouped')<th>{{ __('Date') }}</th><th>#</th>@else<th>#</th><th>{{ __('Date') }}</th>@endif<th>{{ __('Unit / Exam Type') }}</th><th class="exam-title">{{ __('Post Name') }}</th><th>{{ __('Time') }}</th><th>{{ __('Candidates') }}</th><th>{{ __('Centers') }}</th><th>{{ __('Boards') }}</th><th>{{ __('Status') }}</th><th class="d-print-none schedule-actions">{{ __('Action') }}</th></tr></thead><tbody>
@forelse($schedules as $schedule)@php($dateKey=$schedule->exam_date->format('Y-m-d'))@php($dateSerial=$previousDate===$dateKey ? $dateSerial+1 : 1)<tr>@if($filters['display']==='flat')<td>{{ \App\Support\Ui::digits($rowOffset+$loop->index+1) }}</td>@endif @if($filters['display']==='flat' || $previousDate!==$dateKey)<td class="text-nowrap" rowspan="{{ $filters['display']==='grouped' ? $dateSpans[$dateKey] : 1 }}"><strong>{{ \App\Support\Ui::date($schedule->exam_date,'d M Y') }}</strong><br><small>{{ \App\Support\Ui::date($schedule->exam_date,'l') }}</small>@if($schedule->exam_date->isToday())<br><span class="badge bg-green-lt">{{ __('Today') }}</span>@endif</td>@endif @if($filters['display']==='grouped')<td>{{ \App\Support\Ui::digits($dateSerial) }}</td>@endif @php($previousDate=$dateKey)<td>@include('schedules.unit-type-cell',['schedule'=>$schedule])</td><td class="exam-title"><a class="fw-bold" href="{{ route('schedules.show',$schedule) }}">{{ \App\Support\Ui::digits($schedule->post_name ?? $schedule->title) }}</a>@if($schedule->post_grade !== null)<br><small>{{ __('Post Grade') }}: {{ \App\Support\Ui::digits($schedule->post_grade) }}</small>@endif @if($schedule->vacant_posts !== null)<br><small>{{ __('Number of Vacant Posts') }}: {{ \App\Support\Ui::digits($schedule->vacant_posts) }}</small>@endif  @if($schedule->ministry)<br><small>{{ \App\Support\Ui::digits($schedule->ministry) }}</small>@endif @if($schedule->reference)<br><small>{{ \App\Support\Ui::digits($schedule->reference) }}</small>@endif @if($schedule->advertisement_number || $schedule->advertisement_year)<br><small>{{ __('Advertisement') }}: {{ \App\Support\Ui::digits($schedule->advertisement_number) }} @if($schedule->advertisement_year)({{ \App\Support\Ui::digits($schedule->advertisement_year) }})@endif</small>@endif</td><td class="text-nowrap">{{ $schedule->timeLabel() }}</td><td class="text-center">{{ \App\Support\Ui::number($schedule->candidate_count) }}</td><td class="text-center">{{ $schedule->isViva() ? '—' : \App\Support\Ui::number($schedule->center_count) }}</td><td class="text-center">@include('schedules.board-cell',['schedule'=>$schedule])</td><td class="status-cell status-{{ $schedule->status }}"><span class="fw-bold">{{ __(config('scheduler.statuses.'.$schedule->status)) }}</span></td><td class="d-print-none schedule-actions"><a class="btn btn-sm btn-outline-primary" href="{{ route('schedules.show',$schedule) }}"><i class="bi bi-eye" aria-hidden="true"></i> {{ __('View') }}</a>@can('edit-schedules') <a class="btn btn-sm btn-outline-secondary mt-1" href="{{ route('schedules.edit',$schedule) }}"><i class="bi bi-pencil-square" aria-hidden="true"></i> {{ __('Edit') }}</a>@endcan @can('manage-system') <a class="btn btn-sm btn-outline-danger mt-1" href="{{ route('schedules.show',$schedule) }}#delete-schedule"><i class="bi bi-trash" aria-hidden="true"></i> {{ __('Delete') }}</a>@endcan</td></tr>
@empty<tr><td colspan="10" class="text-center text-secondary p-4">{{ __('No exams match these filters.') }}</td></tr>@endforelse
</tbody></table></div><div class="card-footer d-print-none">{{ $pagination->links('shared.pagination',['groupedDates'=>$filters['display']==='grouped']) }}</div></div>
@endsection
