@extends('layouts.app')
@section('title',__('Exam Schedules'))
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h1 class="page-title">{{ __('Exam Schedules') }}</h1><div class="text-secondary">{{ \App\Support\Ui::date($filters['from'],'d M Y') }} – {{ \App\Support\Ui::date($filters['to'],'d M Y') }} · {{ __('Bangladesh time') }}</div></div>@can('edit-schedules')<a class="btn btn-primary" href="{{ route('schedules.create') }}">{{ __('Add Exam Schedule') }}</a>@endcan</div>
<div class="row g-3 mb-3">@foreach(['exams'=>'Exams','candidates'=>'Candidates','centers'=>'Centers','boards'=>'Viva Boards'] as $key=>$label)<div class="col-6 col-lg-3"><div class="card card-body"><div class="text-secondary">{{ __($label) }}</div><div class="h1 mb-0">{{ \App\Support\Ui::number($summary[$key]) }}</div></div></div>@endforeach</div>
<form class="card card-body mb-3 d-print-none" method="get" action="{{ route('schedules.index') }}"><div class="row g-3">
<div class="col-12 col-md-4 col-lg-2"><label class="form-label" for="date"><i class="bi bi-calendar3" aria-hidden="true"></i> {{ __('Single Date') }}</label><input class="form-control" type="date" id="date" name="date" value="{{ request('date') }}"><small class="form-hint">{{ __('Overrides the date range') }}</small></div>
<div class="col-6 col-md-4 col-lg-2"><label class="form-label" for="from"><i class="bi bi-calendar3" aria-hidden="true"></i> {{ __('From') }}</label><input class="form-control" type="date" id="from" name="from" value="{{ $filters['from'] }}"></div><div class="col-6 col-md-4 col-lg-2"><label class="form-label" for="to"><i class="bi bi-calendar3" aria-hidden="true"></i> {{ __('To') }}</label><input class="form-control" type="date" id="to" name="to" value="{{ $filters['to'] }}"></div>
<div class="col-12 col-md-4 col-lg-3"><label class="form-label" for="exam_type"><i class="bi bi-list-check" aria-hidden="true"></i> {{ __('Exam Type') }}</label><select class="form-select" id="exam_type" name="exam_type"><option value="">{{ __('All exam types') }}</option>@foreach(config('scheduler.types') as $code=>$type)<option value="{{ $code }}" @selected(($filters['exam_type'] ?? '')===$code)>{{ __($type['label']) }}</option>@endforeach</select></div>
<div class="col-12 col-md-4 col-lg-3"><label class="form-label" for="unit"><i class="bi bi-building" aria-hidden="true"></i> {{ __('Unit') }}</label><select class="form-select" id="unit" name="unit"><option value="">{{ __('All units') }}</option>@foreach(config('scheduler.units') as $unit)<option value="{{ $unit }}" @selected(($filters['unit'] ?? '')===$unit)>{{ __($unit) }}</option>@endforeach</select></div>
<div class="col-12 col-md-4"><label class="form-label" for="status"><i class="bi bi-check-circle" aria-hidden="true"></i> {{ __('Status') }}</label><select class="form-select" id="status" name="status"><option value="">{{ __('All statuses') }}</option>@foreach(config('scheduler.statuses') as $code=>$label)<option value="{{ $code }}" @selected(($filters['status'] ?? '')===$code)>{{ __($label) }}</option>@endforeach</select></div>
<div class="col-12 col-md-5"><label class="form-label" for="search"><i class="bi bi-search" aria-hidden="true"></i> {{ __('Exam title / reference') }}</label><input class="form-control" id="search" name="search" value="{{ $filters['search'] ?? '' }}" maxlength="200"></div>
<div class="col-12 col-md-3 align-self-end d-flex gap-2 filter-actions"><button class="btn btn-primary"><i class="bi bi-funnel" aria-hidden="true"></i> {{ __('Apply Filters') }}</button><a class="btn btn-outline-secondary" href="{{ route('dashboard') }}"><i class="bi bi-calendar-week" aria-hidden="true"></i> {{ __('This Week') }}</a></div>
</div></form>
@if($summary['candidates_unspecified'])<p class="text-secondary small">{{ __('Candidate counts are not entered for :count exams. The total includes entered counts only.', ['count'=>\App\Support\Ui::digits($summary['candidates_unspecified'])]) }}</p>@endif
<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><span class="text-secondary small">{{ __('Counts include all matching statuses. Filter to Scheduled for active totals.') }}</span><div class="d-flex flex-wrap gap-2 d-print-none">@foreach(['xlsx'=>'Export XLSX','pdf'=>'Export PDF','print'=>'Print'] as $format=>$label)<a class="btn btn-outline-primary btn-sm" @if($format==='print')target="_blank" rel="noopener"@endif href="{{ route('schedules.export',array_merge($filters,['format'=>$format,'page'=>null])) }}"><i class="bi bi-{{ ['xlsx'=>'file-earmark-excel','pdf'=>'file-earmark-pdf','print'=>'printer'][$format] }}" aria-hidden="true"></i> {{ __($label) }}</a>@endforeach</div></div>
<div class="card"><div class="table-responsive"><table class="table table-bordered table-vcenter schedule-table mb-0"><thead><tr><th>#</th><th>{{ __('Date') }}</th><th>{{ __('Exam Type / Post Name') }}</th><th>{{ __('Unit') }}</th><th>{{ __('Start') }}</th><th>{{ __('End') }}</th><th>{{ __('Candidates') }}</th><th>{{ __('Centers') }}</th><th>{{ __('Boards') }}</th><th>{{ __('Status') }}</th><th class="d-print-none">{{ __('Action') }}</th></tr></thead><tbody>
@forelse($schedules as $schedule)<tr><td>{{ \App\Support\Ui::digits($schedules->firstItem()+$loop->index) }}</td><td class="text-nowrap"><strong>{{ \App\Support\Ui::date($schedule->exam_date,'d M Y') }}</strong><br><small>{{ \App\Support\Ui::date($schedule->exam_date,'l') }}</small>@if($schedule->exam_date->isToday())<br><span class="badge bg-green-lt">{{ __('Today') }}</span>@endif</td><td class="exam-title"><small class="text-secondary">{{ $schedule->typeLabel() }}</small><br><a class="fw-bold" href="{{ route('schedules.show',$schedule) }}">{{ $schedule->post_name ?? $schedule->title }}</a>@if($schedule->post_grade !== null)<br><small>{{ __('Post Grade') }}: {{ \App\Support\Ui::digits($schedule->post_grade) }}</small>@endif @if($schedule->ministry)<br><small>{{ $schedule->ministry }}</small>@endif @if($schedule->reference)<br><small>{{ $schedule->reference }}</small>@endif @if($schedule->advertisement_number || $schedule->advertisement_year)<br><small>{{ __('Advertisement') }}: {{ $schedule->advertisement_number }} @if($schedule->advertisement_year)({{ \App\Support\Ui::digits($schedule->advertisement_year) }})@endif</small>@endif</td><td>{{ __($schedule->unit) }}</td><td>{{ $schedule->start_time ? \App\Support\Ui::date($schedule->start_time,'h:i A') : '—' }}</td><td>{{ $schedule->end_time ? \App\Support\Ui::date($schedule->end_time,'h:i A') : '—' }}</td><td class="text-center">{{ \App\Support\Ui::number($schedule->candidate_count) }}</td><td class="text-center">{{ $schedule->isViva() ? '—' : \App\Support\Ui::number($schedule->center_count) }}</td><td class="text-center">{{ $schedule->isViva() ? \App\Support\Ui::number($schedule->board_count) : '—' }}</td><td class="status-cell status-{{ $schedule->status }}"><span class="fw-bold">{{ __(config('scheduler.statuses.'.$schedule->status)) }}</span></td><td class="d-print-none"><a class="btn btn-sm btn-outline-primary" href="{{ route('schedules.show',$schedule) }}"><i class="bi bi-eye" aria-hidden="true"></i> {{ __('View') }}</a>@can('edit-schedules') <a class="btn btn-sm btn-outline-secondary mt-1" href="{{ route('schedules.edit',$schedule) }}"><i class="bi bi-pencil-square" aria-hidden="true"></i> {{ __('Edit') }}</a>@endcan</td></tr>
@empty<tr><td colspan="11" class="text-center text-secondary p-4">{{ __('No exams scheduled for this date range.') }}</td></tr>@endforelse
</tbody></table></div><div class="card-footer d-print-none">{{ $schedules->links() }}</div></div>
@endsection
