<!doctype html><html lang="{{ app()->getLocale() }}"><head><meta charset="utf-8">@include('shared.favicon')<title>{{ __('Exam Schedules') }}</title><meta name="csrf-token" content="{{ csrf_token() }}"><style>
@page { size:A4 landscape; margin:14mm 12mm 18mm; }
@font-face {font-family:Nikosh;src:url('{{ asset('fonts/Nikosh.ttf') }}') format('truetype');}
body { font-family:{{ app()->getLocale()==='bn' ? 'Nikosh':'DejaVu Sans' }},Nikosh,Arial,sans-serif; font-size:9px; color:#111; }
h1 { font-size:16px; text-align:center; margin:0 0 5px; } h2 { font-size:12px; text-align:center; margin:0 0 5px; }
p { margin:5px 0 10px; text-align:center; } table { width:100%; border-collapse:collapse; table-layout:fixed; }
th,td { border:1px solid #555; padding:5px 3px; word-wrap:break-word; } th { background:#edf3f0; } thead { display:table-header-group; } tr { page-break-inside:avoid; } .center { text-align:center; }
.credit { position:fixed; bottom:-10mm; left:0; font-size:8px; color:#555; } .tools { margin:15px; text-align:center; }
@media print { .tools { display:none; } }
</style></head><body data-print-error="{{ __('Print request could not be recorded. Please try again.') }}">
@if($printing)<div class="tools"><button type="button" data-print data-audit-url="{{ route('schedules.print-audit') }}" data-report-token="{{ $reportToken ?? '' }}">{{ __('Print Schedule') }}</button></div>@endif
<h1>{{ __('Bangladesh Public Service Commission (BPSC)') }}</h1><h2>{{ __('Examination Schedule') }}</h2><p>{{ \App\Support\Ui::date($filters['from']) }} — {{ \App\Support\Ui::date($filters['to']) }} · {{ __('Bangladesh time (UTC+6)') }} · {{ __('Exams') }}: {{ \App\Support\Ui::number($schedules->count()) }}<br>{{ __('Filters:') }} {{ __(config('scheduler.types.'.($filters['exam_type'] ?? '').'.label','All exam types')) }} / {{ __($filters['unit'] ?? 'All units') }} / {{ __(config('scheduler.statuses.'.($filters['status'] ?? ''),'All statuses')) }}@if(!empty($filters['search'])) / {{ __('Search:') }} {{ $filters['search'] }}@endif</p>
<table><thead><tr><th style="width:3%">#</th><th style="width:10%">{{ __('Date') }}</th><th style="width:24%">{{ __('Exam Type / Post Name / Post Code') }}</th><th style="width:9%">{{ __('Unit') }}</th><th style="width:7%">{{ __('Start') }}</th><th style="width:7%">{{ __('End') }}</th><th style="width:8%">{{ __('Candidates') }}</th><th style="width:6%">{{ __('Centers') }}</th><th style="width:6%">{{ __('Boards') }}</th><th style="width:9%">{{ __('Status') }}</th></tr></thead><tbody>
@forelse($schedules as $s)<tr><td class="center">{{ \App\Support\Ui::digits($loop->iteration) }}</td><td class="center">{{ \App\Support\Ui::date($s->exam_date,'d M Y') }}<br>{{ \App\Support\Ui::date($s->exam_date,'l') }}</td><td>{{ $s->typeLabel() }}<br><strong>{{ $s->post_name ?? $s->title }}</strong>@if($s->ministry)<br>{{ $s->ministry }}@endif @if($s->reference)<br>{{ $s->reference }}@endif @if($s->advertisement_number || $s->advertisement_year)<br><small>{{ __('Advertisement') }}: {{ $s->advertisement_number }} @if($s->advertisement_year)({{ \App\Support\Ui::digits($s->advertisement_year) }})@endif</small>@endif</td><td class="center">{{ __($s->unit) }}</td><td class="center">{{ $s->start_time ? \App\Support\Ui::date($s->start_time,'h:i A') : '—' }}</td><td class="center">{{ $s->end_time ? \App\Support\Ui::date($s->end_time,'h:i A') : '—' }}</td><td class="center">{{ \App\Support\Ui::number($s->candidate_count) }}</td><td class="center">{{ $s->isViva() ? '—' : \App\Support\Ui::number($s->center_count) }}</td><td class="center">{{ $s->isViva() ? \App\Support\Ui::number($s->board_count) : '—' }}</td><td class="center" style="background-color:#{{ config('scheduler.status_colors.'.$s->status, 'F1F3F5') }};font-weight:bold">{{ __(config('scheduler.statuses.'.$s->status)) }}</td></tr>@empty<tr><td colspan="10" class="center">{{ __('No exams scheduled for this date range.') }}</td></tr>@endforelse
</tbody></table><div class="credit">{{ __('Software Developed By:') }} <strong>{{ __('IT Section, BPSC') }}</strong> · {{ __('Printed:') }} {{ \App\Support\Ui::date(now(),'d M Y h:i A') }}</div>
@if($printing)@vite(['resources/js/app.js'])@endif
</body></html>
