@extends('layouts.app')
@section('title',__('Exam Details'))
@section('content')
<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><h1 class="page-title">{{ __('Exam Details') }}</h1><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="{{ route('schedules.index') }}"><i class="bi bi-arrow-left" aria-hidden="true"></i> {{ __('Back') }}</a>@can('edit-schedules')<a class="btn btn-primary" href="{{ route('schedules.edit',$schedule) }}">{{ __('Edit Schedule') }}</a>@endcan</div></div>
<div class="card card-body mb-3"><h2>{{ $schedule->post_name ?? $schedule->title }}</h2><div class="row g-3">
@foreach(['Exam Type'=>$schedule->typeLabel(),'Post Name'=>$schedule->post_name ?? '—','Ministry/Organization'=>$schedule->ministry ?? '—','Post Code'=>$schedule->reference ?? '—','Advertisement Number'=>$schedule->advertisement_number ?? '—','Advertisement Year'=>\App\Support\Ui::digits($schedule->advertisement_year ?? '—'),'Unit'=>__($schedule->unit),'Date'=>\App\Support\Ui::date($schedule->exam_date,'d M Y (l)'),'Start Time'=>$schedule->start_time ? \App\Support\Ui::date($schedule->start_time,'h:i A') : '—','End Time'=>$schedule->end_time ? \App\Support\Ui::date($schedule->end_time,'h:i A') : '—','Candidates'=>\App\Support\Ui::number($schedule->candidate_count),($schedule->isViva() ? 'Boards':'Centers')=>\App\Support\Ui::number($schedule->isViva() ? $schedule->board_count : $schedule->center_count),'Status'=>__(config('scheduler.statuses.'.$schedule->status)),'Last Updated'=>\App\Support\Ui::date($schedule->updated_at,'d M Y h:i A')] as $label=>$value)<div class="col-6 col-md-4"><div class="text-secondary small">{{ __($label) }}</div><strong>{{ $value }}</strong></div>@endforeach
<div class="col-12"><div class="text-secondary small">{{ __('Notes/Remarks') }}</div><div style="white-space:pre-wrap;overflow-wrap:anywhere">{{ $schedule->notes ?? '—' }}</div></div></div></div>
@can('manage-system')<form method="post" action="{{ route('schedules.destroy',$schedule) }}" class="card card-body" data-confirm-delete data-confirm-message="{{ __('Delete this record? This action will be audited.') }}">@csrf @method('DELETE')<input type="hidden" name="version" value="{{ $schedule->version }}"><label for="confirmation" class="form-label"><i class="bi bi-exclamation-circle" aria-hidden="true"></i> {{ __('Type DELETE to delete this schedule. Audit history will remain.') }}</label><div class="d-flex flex-wrap gap-2"><input class="form-control w-auto" id="confirmation" name="confirmation" required pattern="DELETE" autocomplete="off"><button class="btn btn-outline-danger">{{ __('Delete Schedule') }}</button></div></form>@endcan
@endsection
